# Default JPEG or WebP quality setting. Default is 75.
quality: 100

# Default hint about what type of image. Currently only used for WebP encoding.
# Default is "photo".
# Valid values are "picture", "photo", "drawing", "icon", or "text".
hint: picture

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor: smart

# You may specify the resampling filter used when resizing an image.
# https://gohugo.io/content-management/image-processing/#resampling-filter
# Valid values are Box, Lanczos, CatmullRom, MitchellNetravali, Linear, NearestNeighbor
# Default: Box
resampleFilter: Lanczos
