tableOfContents:
  startLevel: 2
  endLevel: 4

goldmark:
  renderer:
    unsafe: true
  parser:
    attribute:
      block: true

highlight:
  codeFences: true
  lineNoStart: 1
  noClasses: false
  tabWidth: 4
